main activity created
MohitGupta121/IES-IPS-Andoid pull request #35
Opened 2022-03-21 07:15 UTC by Shashank-1302

2022-03-21 07:18 UTC, Shashank-1302 commented
<img width="236" alt="Screenshot 2022-03-21 124602" src="https://user-images.githubusercontent.com/88894042/159218709-9bf63d0b-19fc-43a7-9483-b97542bf2e3a.png">
<img width="179" alt="Screenshot 2022-03-21 124627" src="https://user-images.githubusercontent.com/88894042/159218760-a1eb9814-b456-4dd7-a465-d121c1796b8a.png">

2022-03-21 07:32 UTC, MohitGupta121 reviewed
Good work

2022-03-21 07:35 UTC, MohitGupta121 requested changes

2022-03-21 07:35 UTC, MohitGupta121 commented on app/src/main/res/drawable/ic_baseline_calendar_month_24.xml
> +    android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
Rename drawable with proper naming

2022-03-21 07:35 UTC, MohitGupta121 commented on app/src/main/res/drawable/ic_baseline_keyboard_arrow_down_24.xml
> +    android:viewportHeight="24" android:viewportWidth="24"
Rename this also like ic_arrow like that

2022-03-21 09:14 UTC, MohitGupta121 commented
@Shashank-1302 I fixed the layout file of mainactivity now check other errors according to Java-To-Kotlin Branch fix that and make build of that branch

2022-03-21 09:15 UTC, Shashank-1302 commented
Ok

2022-03-28 08:42 UTC, MohitGupta121 approved these changes

2022-03-28 08:42 UTC, MohitGupta121 approved these changes
Great Work, Thanks for your PR

2022-03-28 08:43 UTC, merged