student result fragment completed
MohitGupta121/IES-IPS-Andoid pull request #42
Opened 2022-04-15 16:50 UTC by ismailbohra

task completed
![Screenshot_20220415_171305](https://user-images.githubusercontent.com/97942595/163598050-72afd465-b505-4cee-8b03-4b6cbf82073e.png)
![Screenshot_20220415_171337](https://user-images.githubusercontent.com/97942595/163598055-ba4a434f-aa09-429d-bec9-a2dfb213c654.png)
![Screenshot_20220415_171353](https://user-images.githubusercontent.com/97942595/163598061-4e2941ce-5341-4b52-bfaa-7125164387be.png)

2022-04-15 17:05 UTC, MohitGupta121 requested changes

2022-04-15 17:05 UTC, MohitGupta121 commented on build.gradle
> +        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.30'
Why you changing build file change it according to development branch.
Not add your local files changes

2022-04-15 17:44 UTC, ismailbohra commented
gradle updated

2022-04-18 08:24 UTC, MohitGupta121 approved these changes
Thanks for your PR.

2022-04-18 09:15 UTC, MohitGupta121 commented
@ismailbohra  upstream your fork repo

2022-04-18 09:15 UTC, merged